- name: blocked
  color: 'fc1423'
- name: bug:confirmed
  color: 'd73a4a'
- name: bug:unverified
  color: 'f9d0c4'
- name: chore
  color: 'ffffff'
- name: ci
  color: '0075ca'
- name: dependencies
  color: '276bd1'
- name: discordjs
  color: '5663e9'
- name: documentation
  color: '0075ca'
- name: duplicate
  color: 'cfd3d7'
- name: feature
  color: 'ffff00'
- name: help wanted
  color: '008672'
- name: need repro
  color: 'c66037'
- name: needs rebase & merge
  color: '24853c'
- name: performance
  color: '80c042'
- name: priority:critical
  color: 'b60205'
- name: priority:high
  color: 'fc1423'
- name: question (please use Discord instead)
  color: 'd876e3'
- name: refactor
  color: '1d637f'
- name: regression
  color: 'ea8785'
- name: semver:major
  color: 'c10f47'
- name: semver:minor
  color: 'e4f486'
- name: semver:patch
  color: 'e8be8b'
- name: tests
  color: 'f06dff'
- name: typings
  color: '80c042'
- name: bun
  color: 'fbf0df'
- name: deno
  color: 'ffffff'
