name: lint

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use (default `20`)
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string

jobs:
  lint:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: lint --fix=false
      operating-system: ${{ inputs.operating-system }}
      node-version: ${{ inputs.node-version }}
      with-submodules: ${{ inputs.with-submodules }}
