name: publish

on:
  workflow_call:
    inputs:
      project-name:
        description: The name of the project
        required: true
        type: string
      node-version:
        description: The version of Node.js to use (default `20`)
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string
      working-directory:
        description: The working directory to run the commands in
        required: false
        default: .
        type: string
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the package version
        required: false
        default: false
        type: boolean
      build:
        description: Whether to run `yarn build` before publishing
        required: false
        default: false
        type: boolean
    secrets:
      NODE_AUTH_TOKEN:
        description: The token to authenticate with the NPM registry
        required: true
      SKYRA_TOKEN:
        description: The token to authenticate with the GitHub repository used to bypass `main` branch checks
        required: true

concurrency:
  group: ${{ github.workflow }}|${{ github.head_ref || github.ref }}|${{ inputs.working-directory }}|${{ inputs.operating-system }}|${{ inputs.node-version }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish ${{ inputs.project-name }}
    runs-on: ${{ inputs.operating-system }}
    if: github.repository_owner == 'sapphiredev'
    permissions:
      id-token: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.SKYRA_TOKEN }}
          submodules: ${{ inputs.with-submodules }}
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: ${{ inputs.node-version }}
      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: inputs.build
        run: yarn build
      - name: Bump Versions and make release
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ "${{ inputs.skip-automatic-bump }}" = "true" ]; then
            yarn bump --skip-automatic-bump
          else
            yarn bump
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to NPM
        working-directory: ${{ inputs.working-directory }}
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          # Detect whether the current Yarn version is eligible for publishing with provenance (v4.9.0 or later)
          FLAG=$([ $(node -p "require('semver').gte('$(yarn --version)', '4.9.0')") = true ] && echo '--provenance' || echo '')

          yarn npm publish ${FLAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
